package com.uwefuchs.demo.soap.apachecxf.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.16
 * 2018-10-02T20:35:30.559+02:00
 * Generated source version: 3.1.16
 * 
 */
@WebServiceClient(name = "BaeldungService", 
                  wsdlLocation = "file:/home/uwe/Downloads/baeldung.wsdl",
                  targetNamespace = "http://endpoint.apachecxf.soap.demo.uwefuchs.com/") 
public class BaeldungService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://endpoint.apachecxf.soap.demo.uwefuchs.com/", "BaeldungService");
    public final static QName BaeldungPort = new QName("http://endpoint.apachecxf.soap.demo.uwefuchs.com/", "BaeldungPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/uwe/Downloads/baeldung.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BaeldungService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/uwe/Downloads/baeldung.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BaeldungService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BaeldungService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BaeldungService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BaeldungService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BaeldungService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BaeldungService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Baeldung
     */
    @WebEndpoint(name = "BaeldungPort")
    public Baeldung getBaeldungPort() {
        return super.getPort(BaeldungPort, Baeldung.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Baeldung
     */
    @WebEndpoint(name = "BaeldungPort")
    public Baeldung getBaeldungPort(WebServiceFeature... features) {
        return super.getPort(BaeldungPort, Baeldung.class, features);
    }

}
