package com.uwefuchs.demo.soap.apachecxf.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.16
 * 2018-10-02T20:35:30.552+02:00
 * Generated source version: 3.1.16
 * 
 */
@WebService(targetNamespace = "http://endpoint.apachecxf.soap.demo.uwefuchs.com/", name = "Baeldung")
@XmlSeeAlso({ObjectFactory.class})
public interface Baeldung {

    @WebMethod
    @RequestWrapper(localName = "helloStudent", targetNamespace = "http://endpoint.apachecxf.soap.demo.uwefuchs.com/", className = "com.uwefuchs.demo.soap.apachecxf.endpoint.HelloStudent")
    @ResponseWrapper(localName = "helloStudentResponse", targetNamespace = "http://endpoint.apachecxf.soap.demo.uwefuchs.com/", className = "com.uwefuchs.demo.soap.apachecxf.endpoint.HelloStudentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String helloStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        com.uwefuchs.demo.soap.apachecxf.endpoint.Student arg0
    );

    @WebMethod
    @RequestWrapper(localName = "hello", targetNamespace = "http://endpoint.apachecxf.soap.demo.uwefuchs.com/", className = "com.uwefuchs.demo.soap.apachecxf.endpoint.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://endpoint.apachecxf.soap.demo.uwefuchs.com/", className = "com.uwefuchs.demo.soap.apachecxf.endpoint.HelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String hello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getStudents", targetNamespace = "http://endpoint.apachecxf.soap.demo.uwefuchs.com/", className = "com.uwefuchs.demo.soap.apachecxf.endpoint.GetStudents")
    @ResponseWrapper(localName = "getStudentsResponse", targetNamespace = "http://endpoint.apachecxf.soap.demo.uwefuchs.com/", className = "com.uwefuchs.demo.soap.apachecxf.endpoint.GetStudentsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.uwefuchs.demo.soap.apachecxf.endpoint.StudentMap getStudents();
}
